version: 2
filters:
  branches:
    only:
      - master

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    environment:
      GO111MODULE: "on"
    steps:
      - checkout

workflows:
  version: 2
  build-workflow:
    jobs:
      - test
